# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iTreCarte
email: davide@reppucci.it
description: Scopri dove si nasconde la K di fiori, la tua carta vincente!
keywords: itrecarte, tre, carte, gioco, azzardo, divertimento, free, game
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://itrecarte.github.io" # the base hostname & protocol for your site
twitter_username: davidereppucci
github_username:  dreppucci

# Build settings
markdown: kramdown
